### ISSUE TITLE
List of unextracted games?

### ISSUE THREAD

**Issue by ghost** [sepalani/GamestatsHTTP#13]
Would it be possible to have some list that tells you what games have their keys extracted (i.e. not just looking in the TXT file) so people can extract keys for games we dont have? :3

**Comment by sepalani** [comment]
Missing ones according to the log:
- pokebattlewii
- sonriders2wii

**Comment by larsenv** [comment]
I can't find a key in either of them. They probably are using GAMESTATS TCP instead.

**Comment by sepalani** [comment]
They are performing the following requests according to the log:
```HTTP
GET /pokebattlewii/web/pbrcheck/check.asp?pid=600264497 HTTP/1.1
```
```HTTP
GET /sonriders2wii/web/client/get2.asp?pid=600263442 HTTP/1.1
```
No doubt they are using Gamestats HTTP. I can't tell for pokebattlewii as it's not using a route I know. However, concerning sonriders2wii I'm pretty confident that it's using Gamestats.

If it's not located in the main.dol, then it could be in any file. With a bit a luck it might be in relocatable files such as REL and RSO files. If not, well... Were you able to locate any information related to the network module (usually they're stored in the same file)? More specifically, the gamename and its secret: https://github.com/sepalani/dwc_network_server_emulator/blob/master/gslist.cfg

**Comment by Agentwii** [comment]
For Trackmania Gamestats check if se key is perfect
t9Sf4yfjf1RtvDu3AA
# 2D74395366347966A6631527476447533414100

**Comment by sepalani** [comment]
@Agentwii 
It's not, moreover we already have its key which is:
> trkmaniawii     TawZhkNAWdyvETbQXNCo0001311d0000296302000000775c72f5

See:
https://github.com/sepalani/GamestatsHTTP/blob/master/project/gamestats_keys.txt#L213

Please don't submit keys if you don't know what you're doing.

**Comment by Agentwii** [comment]
Tell me more about this I have not found in the file dol trackmania

**Comment by Agentwii** [comment]
Do trackmania games have gamestat and tcp?

**Comment by larsenv** [comment]
- `gauntletds` - apparently that video game was cancelled
- `nanostray2ds` and `nanost2EUds` - I can't seem to find the key for these - is it using gamestats TCP?
- `lostmagicwii` - Found the key, it was in the REL file

**Comment by barronwaffles** [comment]
`gauntletds` was released/leaked as a nearly complete prototype, the rom should be obtainable from the usual sources.

Didn't have much luck with `nanostray2ds` / `nanost2EUds` myself, but it definitely uses GStats2

**Comment by sepalani** [comment]
@barronwaffles Do you know which routes they use? If these aren't the usual ones, the actual regular expressions might not work. The issues I had with DS games is when they're in the overlay, they all need to be decompressed first before looking for the secret. Usually, they're always near the network code.

**Comment by barronwaffles** [comment]
@sepalani From memory all of those titles were just standard get2/put2 routes.

I had used a script that extracted the arm9.bin + overlays, processed a temporary copy of each with the decompression tools, flagged any potential URL / URL path fragments and then ran the stats key regular expression.

Those were the only titles (I *think*) where it flagged possible gamestats2 URLs but didn't manage to find a key. When I have a chance I'll dig everything up and upload the script/s and output.

**Comment by InternalLoss** [comment]
`mswinterds` is missing from the key list, and the server throws a lovely error due to missing keys.

**Comment by InternalLoss** [comment]
Pretty sure Larsen ran extraction scripts across the whole Wii/NDS library - is this still a necessary issue?
